[build]
builder = "nixpacks"
buildCommand = "npm install && cd server && npm install --omit=dev"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
